package com.example.util

import androidx.compose.runtime.Immutable

@Immutable
data class HisabStrings(
    val appName: String,
    val subtitle: String,
    val greetingMorning: String,
    val greetingAfternoon: String,
    val greetingEvening: String,
    val moneyOverview: String,
    val navHome: String,
    val navTransactions: String,
    val navPeople: String,
    val navShops: String,
    val navNotes: String,
    val navMore: String,
    val cashBalance: String,
    val openingBalance: String,
    val todayTitle: String,
    val currentPositionTitle: String,
    val quickActionsTitle: String,
    val recentActivityTitle: String,
    val income: String,
    val expense: String,
    val moneyReceived: String,
    val moneyGiven: String,
    val receivable: String,
    val payable: String,
    val shopDue: String,
    val activeLoans: String,
    val giveMoney: String,
    val takeMoney: String,
    val receivePayment: String,
    val payMoney: String,
    val loan: String,
    val addTransaction: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val undo: String,
    val transactionSaved: String,
    val transactionDeleted: String,
    val searchPlaceholder: String,
    val noTransactionsYet: String,
    val addFirstTransaction: String,
    val noShopsYet: String,
    val createFirstShop: String,
    val noPeopleYet: String,
    val addFirstPerson: String,
    val noLoansYet: String,
    val youreAllClear: String,
    val welcomeToHisab: String,
    val chooseCurrency: String,
    val startingCashBalance: String,
    val getStarted: String,
    val skipSetup: String,
    val amountLabel: String,
    val productOrDescLabel: String,
    val noteLabel: String,
    val selectShop: String,
    val selectPerson: String,
    val selectCategory: String,
    val addDue: String,
    val currentDue: String,
    val totalReceived: String,
    val owesMe: String,
    val iOwe: String,
    val borrow: String,
    val repay: String,
    val loansSection: String,
    val reportsSection: String,
    val categoriesSection: String,
    val backupSection: String,
    val customizationSection: String,
    val settingsSection: String,
    val securitySection: String,
    val iBorrowedMoney: String,
    val iLentMoney: String,
    val exportFullBackup: String,
    val importBackup: String,
    val exportTransactionsCsv: String,
    val errorSaveTransaction: String
)

object AppStrings {
    val English = HisabStrings(
        appName = "Hisab",
        subtitle = "Personal Finance & Digital হিসাব খাতা",
        greetingMorning = "Good morning 👋",
        greetingAfternoon = "Good afternoon 👋",
        greetingEvening = "Good evening 👋",
        moneyOverview = "Your money overview",
        navHome = "Home",
        navTransactions = "Transactions",
        navPeople = "People",
        navShops = "Shops",
        navNotes = "To-Do",
        navMore = "More",
        cashBalance = "Cash Balance",
        openingBalance = "Opening Balance",
        todayTitle = "Today",
        currentPositionTitle = "Current Position",
        quickActionsTitle = "Quick Actions",
        recentActivityTitle = "Recent Activity",
        income = "Income",
        expense = "Expense",
        moneyReceived = "Money Received",
        moneyGiven = "Money Given",
        receivable = "Receivable",
        payable = "Payable",
        shopDue = "Shop Due",
        activeLoans = "Active Loans",
        giveMoney = "Give Money",
        takeMoney = "Take Money",
        receivePayment = "Receive",
        payMoney = "Pay",
        loan = "Loan",
        addTransaction = "Add Transaction",
        save = "Save",
        cancel = "Cancel",
        delete = "Delete",
        edit = "Edit",
        undo = "Undo",
        transactionSaved = "Transaction saved",
        transactionDeleted = "Transaction deleted",
        searchPlaceholder = "Search shops, people, products, notes, IDs...",
        noTransactionsYet = "No transactions yet.",
        addFirstTransaction = "Add your first transaction",
        noShopsYet = "No shops yet.",
        createFirstShop = "Create your first shop",
        noPeopleYet = "No people added yet.",
        addFirstPerson = "Add a person to track lending & borrowing",
        noLoansYet = "No loans.",
        youreAllClear = "You're all clear",
        welcomeToHisab = "Welcome to Hisab",
        chooseCurrency = "Choose currency",
        startingCashBalance = "Starting cash balance",
        getStarted = "Get Started",
        skipSetup = "Skip",
        amountLabel = "Amount",
        productOrDescLabel = "Product / Description",
        noteLabel = "Note (Optional)",
        selectShop = "Select Shop",
        selectPerson = "Select Person",
        selectCategory = "Select Category",
        addDue = "+ Add Due",
        currentDue = "Current Due",
        totalReceived = "Total Received",
        owesMe = "owes me",
        iOwe = "I owe",
        borrow = "Borrow",
        repay = "Repay",
        loansSection = "Loans",
        reportsSection = "Reports",
        categoriesSection = "Categories",
        backupSection = "Backup & Restore",
        customizationSection = "Customization",
        settingsSection = "Settings",
        securitySection = "App Lock & Security",
        iBorrowedMoney = "I Borrowed Money",
        iLentMoney = "I Lent Money",
        exportFullBackup = "Export Full Backup (JSON)",
        importBackup = "Import Backup (JSON)",
        exportTransactionsCsv = "Export Transactions CSV",
        errorSaveTransaction = "This transaction could not be saved. Please check the information and try again."
    )

    val Bangla = HisabStrings(
        appName = "হিসাব",
        subtitle = "ব্যক্তিগত অর্থ ও ডিজিটাল হিসাব খাতা",
        greetingMorning = "শুভ সকাল 👋",
        greetingAfternoon = "শুভ অপরাহ্ন 👋",
        greetingEvening = "শুভ সন্ধ্যা 👋",
        moneyOverview = "আপনার টাকার সারসংক্ষেপ",
        navHome = "হোম",
        navTransactions = "লেনদেন",
        navPeople = "মানুষজন",
        navShops = "দোকান বাকি",
        navNotes = "টু-ডু",
        navMore = "আরও",
        cashBalance = "নগদ ব্যালেন্স",
        openingBalance = "শুরুর ব্যালেন্স",
        todayTitle = "আজকের হিসাব",
        currentPositionTitle = "বর্তমান অবস্থা",
        quickActionsTitle = "দ্রুত এন্ট্রি",
        recentActivityTitle = "সাম্প্রতিক লেনদেন",
        income = "আয়",
        expense = "ব্যয়",
        moneyReceived = "টাকা প্রাপ্তি",
        moneyGiven = "টাকা প্রদান",
        receivable = "পাওনা (Receivable)",
        payable = "দেনা (Payable)",
        shopDue = "দোকানের বাকি (দেনা)",
        activeLoans = "চলমান ঋণ",
        giveMoney = "টাকা দিন",
        takeMoney = "টাকা নিন",
        receivePayment = "আদায়",
        payMoney = "পরিশোধ",
        loan = "ঋণ",
        addTransaction = "নতুন লেনদেন",
        save = "সংরক্ষণ",
        cancel = "বাতিল",
        delete = "মুছুন",
        edit = "সম্পাদনা",
        undo = "পূর্বাবস্থায় ফেরান",
        transactionSaved = "লেনদেন সংরক্ষিত হয়েছে",
        transactionDeleted = "লেনদেন মুছে ফেলা হয়েছে",
        searchPlaceholder = "দোকান, মানুষ, পণ্য, নোট বা টু-ডু খুঁজুন...",
        noTransactionsYet = "এখনও কোনো লেনদেন নেই।",
        addFirstTransaction = "আপনার প্রথম লেনদেন যোগ করুন",
        noShopsYet = "এখনও কোনো দোকান যোগ করা হয়নি।",
        createFirstShop = "দোকানের হিসাব রাখতে দোকান যোগ করুন",
        noPeopleYet = "এখনও কাউকে যোগ করা হয়নি।",
        addFirstPerson = "লেনদেন ট্র্যাক করতে মানুষজন যোগ করুন",
        noLoansYet = "কোনো ঋণ নেই।",
        youreAllClear = "আপনার কোনো বকেয়া ঋণ নেই",
        welcomeToHisab = "হিসাব-এ স্বাগতম",
        chooseCurrency = "মুদ্রা নির্বাচন করুন",
        startingCashBalance = "শুরুর নগদ ব্যালেন্স",
        getStarted = "শুরু করুন",
        skipSetup = "এড়িয়ে যান",
        amountLabel = "পরিমাণ (Amount)",
        productOrDescLabel = "পণ্য / বিবরণ",
        noteLabel = "নোট (ঐচ্ছিক)",
        selectShop = "দোকান নির্বাচন করুন",
        selectPerson = "ব্যক্তি নির্বাচন করুন",
        selectCategory = "ক্যাটাগরি নির্বাচন করুন",
        addDue = "+ বাকিতে কেনাকাটা",
        currentDue = "দোকানদার পাবেন",
        totalReceived = "মোট পরিশোধ",
        owesMe = "আমার কাছে ধার",
        iOwe = "আমি ধার আছি",
        borrow = "ধার নিন",
        repay = "পরিশোধ করুন",
        loansSection = "ঋণ ব্যবস্থাপনা",
        reportsSection = "রিপোর্ট ও বিশ্লেষণ",
        categoriesSection = "ক্যাটাগরি",
        backupSection = "ব্যাকআপ ও রিস্টোর",
        customizationSection = "কাস্টমাইজেশন ও থিম",
        settingsSection = "সেটিংস",
        securitySection = "অ্যাপ লক ও নিরাপত্তা",
        iBorrowedMoney = "আমি ঋণ নিয়েছি",
        iLentMoney = "আমি ঋণ দিয়েছি",
        exportFullBackup = "সম্পূর্ণ ব্যাকআপ এক্সপোর্ট (JSON)",
        importBackup = "ব্যাকআপ ইমপোর্ট করুন (JSON)",
        exportTransactionsCsv = "লেনদেন CSV এক্সপোর্ট করুন",
        errorSaveTransaction = "লেনদেনটি সংরক্ষণ করা যায়নি। অনুগ্রহ করে তথ্য যাচাই করে আবার চেষ্টা করুন।"
    )

    fun forLanguage(code: String): HisabStrings =
        if (code == "bn") Bangla else English
}
